---
title: "Er det høyde som bestemmer inntekt?"
output: html_notebook
lang: no-NB
---

```{r}
library(ggplot2)
library(tinytex)
library(tidyverse)
library(modelr)
library(ggpubr)
options(scipen = 999)
```

# Kort innledning 

# Kort litteraturgjennomgang på en side.

# Analyse

```{r Hoyde}
hoyde <- heights
```

# Beskrivende statestikk
Se på dette senere. 

# EDA

```{r}
#Slett dette senere?
ggplot(data = hoyde)
```


## Lag et histogram av variablen *income*

```{r}
ggplot(data = hoyde, aes(income)) +
  geom_histogram()
```

## Forklaringen på utliggerne langt til høyre

## Personer uten inkludert i datasettet? 

```{r}
sum(hoyde$income == 0)
```


# Regresjonsanalyse

```{r}
hoyde <- heights
```

## Redusert datasett

```{r}
# Kan slettes, skrevet lengre oppe
hoyde_begr <- hoyde %>% 
  filter(inntekt < 1500000,
         inntekt > 1)
```


## Lag to nye variabler + lag ny variabel bmi

```{r}
hoyde <- hoyde %>% 
  mutate(inntekt = income * 8.42,
         hoyde_cm = height * 2.54,
         vekt_kg = weight * 0.454,
         BMI = (vekt_kg/hoyde_cm)^2)
```


```{r}
ggplot(data = hoyde, aes(x = inntekt)) + 
  geom_histogram()
```


```{r}
hoyde_begr <- hoyde %>% 
  filter(income < 1500000,
         income > 1)
```

```{r}
ggplot(data = hoyde_begr, aes(x = income)) + 
  geom_histogram ()
```

```{r}
#slett senere, for å forstå det bedre
sum(hoyde$income == 0)
sum(hoyde$income < 1500000)
7006-5123
```

```{r}
lm(income ~ hoyde_cm, data = hoyde) %>%  
  summary()
```

```{r}
lm(inntekt ~ hoyde_cm, data = hoyde) %>% 
  summary()
```


```{r}
 -1337837.4 + (9884.6 *173)
-1337837.4 + (9884.6 *161)
```
```{r}
lm(inntekt ~ hoyde_cm + vekt_kg, data = hoyde_begr) %>% 
  summary()
```


```{r}
-697374.7 + (6735.7*173) + (-691.5*70)
```
```{r}
hoyde <- hoyde %>% 
mutate(
  married = factor(
    case_when(
      marital == 'married' ~ TRUE,
      TRUE ~ FALSE
      )
    )
  )
```

## minst 6 


# Test, kan sikkert bare slettes 
```{r}
attach(heights)
summary(income)
histogram(income)
```

 

